Aad 717 notifications
SkillsFundingAgency/das-apprentice-app pull request #103
Opened 2024-12-10 14:31 UTC by CathyGroom

2024-12-12 16:39 UTC, alireid requested changes
Couple minor bits

2024-12-12 16:40 UTC, alireid commented on src/SFA.DAS.ApprenticeApp.Application/SFA.DAS.ApprenticeApp.Application.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
Is this necessary through the whole codebase?

2024-12-13 09:14 UTC, CathyGroom commented on src/SFA.DAS.ApprenticeApp.Pwa/Controllers/NotificationsController.cs
> +        //[Authorize]
I've updated both methods

2024-12-13 09:30 UTC, alireid approved these changes

2024-12-16 15:50 UTC, merged