Aad 327 progress bar
SkillsFundingAgency/das-apprentice-app pull request #36
Opened 2024-07-16 13:29 UTC by tdavande

2024-07-18 07:52 UTC, alireid submitted a review, later dismissed

2024-07-22 13:38 UTC, alireid requested changes

2024-07-22 13:38 UTC, alireid commented on src/SFA.DAS.ApprenticeApp.Pwa/Views/Profile/Index.cshtml
> +<head>
Not sure why we are including <head> here, this is included in layout..

2024-07-22 13:48 UTC, alireid approved these changes

2024-07-22 13:49 UTC, alireid submitted a review, later dismissed

2024-07-22 14:20 UTC, vinbapps approved these changes
all ok

2024-07-22 14:20 UTC, merged